# Create and Use a ConfigMap in a Pod

# Create a ConfigMap named app-config in the default namespace with the following key-value pairs:

#LOG_LEVEL: debug
#MAX_RETRIES: 5
#Then, create a pod named app-pod that uses the busybox image and mounts the LOG_LEVEL value as an environment variable and MAX_RETRIES as a file located at /config/MAX_RETRIES inside the pod.

#k create cm app-config --from-literal=LOG_LEVEL=DEBUG --from-literal=MAX_RETRIES=5 
#k run app-pod --image=busybox -oyaml --dry-run=client >> q1.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: app-config
data:
  LOG_LEVEL: "debug"
  MAX_RETRIES: "5"
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app-pod
  name: app-pod
spec:
  containers:
  - image: busybox
    name: app-pod
    env:
        - name: LOG_LEVEL  
          valueFrom:
            configMapKeyRef:
              name: app-config            
              key: LOG_LEVEL
    volumeMounts:
    - name: max-retries
      mountPath: /config/MAX_RETRIES          
  volumes:
  - name: max-retries
    configMap:
      name: app-config
      items:
      - key: "MAX_RETRIES"
        path: "MAX_RETRIES"
      