apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-container-pod
  name: multi-container-pod
spec:
  volumes:
  - name: logvol
    emptyDir: {}
  containers:
  - image: nginx:latest
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: logvol
      mountPath: /var/log/nginx
    resources: {}
  - image: busybox
    name: logger
    command: [ "sh", "-c", "while true; do cat /var/log/nginx/access.log; sleep 5; done" ]
    volumeMounts:
    - name: logvol
      mountPath: /var/log/nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
