#Create a ConfigMap named env-config with the following key-value pairs:
# ENV1: Value1
# ENV2: Value2
# ENV3: Value3
# Create a pod named env-pod using the busybox image and configure it to use all keys 
# from env-config as environment variables. Verify that each environment variable is accessible in the pod.
#
# % k create cm app-config --from-literal=ENV1=Value1 --from-literal=ENV2=Value2 --from-literal=ENV3=Value3
# % k run env-pod --image=busybox  -oyaml --dry-run=client > q4.yaml
# % k exec pod/env-pod -- env
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: env-config
data:
  ENV1: Value1
  ENV2: Value2
  ENV3: Value3
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: env-pod
  name: env-pod
spec:
  containers:
  - image: busybox
    name: env-pod
    command:
    - 'sh'
    - '-c'
    - 'sleep 36000'
    envFrom: 
      - configMapRef: 
          name: env-config
